projects:
  mwicnyapp-devf:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: r4cfqsynq5h7njs6bshudf4r5y
        maxDepth: 4
extensions:
  amplify:
    version: 3
